### PR TITLE
# Atomic Bomb Comit

### PR DESCRIPTION
**Pull request by MizMahem**
So this submits a (mostly) fully functional port of NetTally to Avalonia.

The goal of this port was not to touch any of the existing core, and not to have any dependancies on the Windows flavor of NetTally. This was almost entirely succesfull.

Lots of changes in here, but these are the highlights.

## Converters
Mostly ported over unchanged though they use the Avalonia.IConvert interface instead, and the attributes were removed. Some converters were removed as they were unneeded, including the multi-bool converter and the bool to visibility converter

## Navigation
  Ported over mostly unchanaged, though the Show and ShowDialog methods were converted to work with Avalonia.

## Views
Most of the changes occured here obviously.
### Universal Changes - General
* Nomanclature of Dialog windows changed, removing Window suffix (did this on accident)
* Warning `MessageBox` replaced with new `ShowWarning` dialog using an avalonia compatible MessageBox replacement.

### Universal Changes Xaml
* Xaml is now AXaml
* Avalonia doesn't have `Label` so those are replaced with `TextBlock`
* `x:Name` has been replaced with `Name` (necessary for Avalonia Binding)
* `Visibility` is replaced with `IsVisible` (and often removed)
* `ListBox` bind to `Items` not to `ItemSource`
* Unnecessary coverters have been removed or replaced with avalonia equivalents (mostly booltovisibility, multibooland, invert bool, and notnull converters)
* Binding has been reworked in places to use Avalonia flavors, especially element names binding.
* ToolTips have been moved to their Avalonia equivalent.
*
### Universal Changes CodeBehind
* Avalonia requires a blank constructor, so those have been implemented, they should not be called.
* Avalonia does not automatically build objects in the codebehind based on `x:Name`, so `FindControl<Control>("ControlName")` has been subsituted for those.
* When a event function was reworked it's naming convention was changed to UpperCamalCase like: `ControlName_Event`

### MainWindow
Actually one of the most unchanged on the xaml side.
  * The edit button was removed as that functionality has been moved into the New/Edit Quest Dialog.
  * Hyperlinks were removed
  * Much of the onfocus functionality was removed.
### QuestOptions
Largely rebuilt
* Now contains the functionality for changing the quest name and url
* Now has a 'cancel' button, ideally this would let a user cancel and edit, but for now it only can cancel adding a new quest.
* Reset buttons have been merged into one control.
* Now just takes a reference to the `Quest` in question instead of the entire ViewModel.
* The remaining statics have been moved to a new class and added to the core.
### GlobalOptions
Xaml Rebuilt
* Xaml rebuilt into groupboxes, layout still a little rough.
* Now just takes a reference to the `Option` instead of the entire ViewModel.
* The remaining statics have been moved to a new class and added to the core.

### ManageVotes
Xaml mostly untouched, codebehind almost entirely rewritten.
* Task Management functionality removed for now.
* The Codebehind basically contains a ViewModel for this dialog. This isn't ideal, but I didn't want to change the current project style in this respect.
### ManageTasks
Not ported, removed.

## Config
Ported over unchanged, but not functional. Not sure what the error is at the moment. Did have to add a dependancy to Config.Manager, not sure if that will affect compatability or not.

# Outstanding Issues
This port is functional except for two big outstanding issues. The config/save functionality is not working, and the logging is not working. So far I haven't been able to get to the bottom of that.

There are numerous small layout issues that probably need to be addressed as well, and as always the documentation should probably be improved.

### CODE REVIEW

**Comment by MizMahem** [comment]
Oh, one other bug I forgot, in Avalonia, the `ResizeToContent="WidthAndHeight"` does not appear to be functioning as I expect, so the windows where I rebuilt things are not sizing as I intended. Not sure if that is an Avalonia thing or a me thing.

**Comment by MizMahem** [comment]
This last commit should correct that assembly dependency, making it dependent on the Configuration.Manager nuget package instead. Still didn't fix the config issue not saving issue not sure what's up with that.

**Comment by Kinematics** [comment]
I'd like to ask that you rebase to the current Dev (which I'll be pushing momentarily), which is a bunch of stuff that I've accumulated locally over the last few months, but hadn't published. Then I can start while on the same page.

Edit: Dev tip is fully updated.

**Comment by Kinematics** [comment]
So, I'd let this languish for far too long, as I basically didn't work on NetTally for the last year.

Part of the issue was a corruption of my local repo, where I couldn't tell which version (out of 4 or 5 possible versions) was the correct one. I finally got around to fixing that a few weeks ago, which reminded me to go back to this pull request.

I rebased this on top of updates to .NET 6 that were part of other changes that happened along with fixing the repo, so it ended up being constructed as PR #11. As such, this PR will be closed.

I went through and fixed all the new issues that showed up from the version update. Fixed the issue with the config not working (and I can't blame you for missing it; it's not obvious). Also did a bunch of fixing on the UI side of things, and re-added the context menu for changing tasks on a vote.

I really do appreciate the rewrite of the ManageVotes window code-behind. The brute force method I used wasn't very pretty.

The main thing leftover is figuring out which builds to publish, since there's getting to be quite a few of them.

**Comment by MizMahem** [comment]
Hey man, great to hear it! Totally fell off my radar as well.

If you don't mind me asking, what was the config issue? That one had me
scratching my head.

**Comment by Kinematics** [comment]
> If you don't mind me asking, what was the config issue? That one had me scratching my head.

The app.config file (an XML file that is not included in new csproj projects by default) contains information that the ConfigurationManager module uses to identify "sections" for configuration data. Without it, the code in ConfigurationHelper that loads config file maps (which are used to find the AppData directory location that's safe to write to) won't find what's needed to load and save data.

The app.config file was part of the .NET Framework project creation, but has largely been obsoleted by other things since the move to .NET Core.  Unfortunately .NET Core doesn't have good read/write configuration; it prefers read-only.  So this is sort of legacy stuff that I've had to carry forward.

**Comment by MizMahem** [comment]
Oh man, so that file being missing was giving me all the grief? Crazy.
Seems like it should have thrown someplace. I thought I was taking crazy
pills tracking down all the calls which all seemed to be working fine
except... no data. I'll keep that in mind for next time :).

**Pull request closed without merging**
